"""empty message

Revision ID: 049024356d09
Revises: a6062680de57
Create Date: 2024-04-15 07:54:03.413884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049024356d09'
down_revision = 'a6062680de57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
