"""empty message

Revision ID: a6062680de57
Revises: b1552242f6fe
Create Date: 2024-04-13 16:55:13.339072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6062680de57'
down_revision = 'b1552242f6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('Dealership', sa.String(length=12), nullable=False))
        batch_op.drop_index('barcode')
        batch_op.drop_index('name')
        batch_op.create_unique_constraint(None, ['model'])
        batch_op.create_unique_constraint(None, ['Dealership'])
        batch_op.drop_column('barcode')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('barcode', mysql.VARCHAR(length=12), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.create_index('barcode', ['barcode'], unique=True)
        batch_op.drop_column('Dealership')
        batch_op.drop_column('model')

    # ### end Alembic commands ###
