"""empty message

Revision ID: c4c0d6e8697a
Revises: f4ae9d7b3a11
Create Date: 2024-08-06 19:12:33.679001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4c0d6e8697a'
down_revision = 'f4ae9d7b3a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('chasis_No', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chasis_No')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email_address', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchasedItems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitingRecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('carof_review', sa.Integer(), nullable=True),
    sa.Column('cust_elgbility', sa.String(length=30), nullable=False),
    sa.Column('booking_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['carof_review'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email_address')

    op.drop_table('user')
    op.drop_table('cart')
    op.drop_table('purchased_items')
    op.drop_table('visiting_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visiting_records',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('visit_date', mysql.DATETIME(), nullable=False),
    sa.Column('carof_review', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cust_elgbility', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('booking_status', mysql.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['carof_review'], ['vehicles.id'], name='visiting_records_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='visiting_records_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('purchased_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='purchased_items_ibfk_1'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='purchased_items_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='cart_ibfk_1'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='cart_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('budget', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_role', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_role'], ['roles.id'], name='user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email_address', ['email_address'], unique=True)

    op.drop_table('visitingRecords')
    op.drop_table('purchasedItems')
    op.drop_table('carts')
    op.drop_table('users')
    op.drop_table('importations')
    # ### end Alembic commands ###
