"""empty message

Revision ID: ecbef2677a0b
Revises: 049024356d09
Create Date: 2024-04-15 08:03:35.952243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbef2677a0b'
down_revision = '049024356d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['user_role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
