"""empty message

Revision ID: f080c9d043bf
Revises: a84f8c72e074
Create Date: 2024-08-06 20:02:06.203938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f080c9d043bf'
down_revision = 'a84f8c72e074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visiting_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('carof_review', sa.Integer(), nullable=True),
    sa.Column('cust_elgbility', sa.String(), nullable=False),
    sa.Column('booking_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['carof_review'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visiting_records')
    # ### end Alembic commands ###
